- name: Affinity Photo 2
  identifier:
    kind: Title
    id: Affinity Photo 2
    matching_strategy: Legacy
  options:
  - force
  float_identifiers:
  - kind: Exe
    id: Photo.exe
    matching_strategy: Equals
- name: Android Studio
  identifier:
    kind: Exe
    id: studio64.exe
    matching_strategy: Equals
  options:
  - object_name_change
- name: Calculator
  identifier:
    kind: Title
    id: Calculator
    matching_strategy: Equals
  float_identifiers:
  - kind: Title
    id: Calculator
    matching_strategy: Equals
- name: CopyQ
  identifier:
    kind: Exe
    id: copyq.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
- name: Docker Desktop
  identifier:
    kind: Exe
    id: Docker Desktop.exe
    matching_strategy: Equals
  options:
  - border_overflow
- name: Figma
  identifier:
    kind: Exe
    id: Figma.exe
    matching_strategy: Equals
  options:
  - border_overflow
- name: GitHub Credential Manager
  identifier:
    kind: Exe
    id: git-credential-manager.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: git-credential-manager.exe
    matching_strategy: Equals
- name: Google Chrome
  identifier:
    kind: Exe
    id: chrome.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
- name: Microsoft Active Accessibility
  identifier:
    kind: Class
    id: ''
    matching_strategy: Legacy
  float_identifiers:
  - kind: Class
    id: '#32770'
    comment: Dialog Box
    matching_strategy: Legacy
- name: Microsoft PC Manager
  identifier:
    kind: Exe
    id: MSPCManager.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: MSPCManager.exe
    matching_strategy: Equals
- name: NVIDIA GeForce Experience
  identifier:
    kind: Exe
    id: NVIDIA GeForce Experience.exe
    matching_strategy: Equals
  options:
  - border_overflow
- name: ONLYOFFICE Editors
  identifier:
    kind: Class
    id: DocEditorsWindowClass
    matching_strategy: Legacy
  options:
  - border_overflow
  - tray_and_multi_window
- name: Obsidian
  identifier:
    kind: Exe
    id: Obsidian.exe
    matching_strategy: Equals
  options:
  - border_overflow
  - force
- name: OneDrive
  identifier:
    kind: Exe
    id: OneDrive.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: OneDriveReactNativeWin32WindowClass
    matching_strategy: Legacy
- name: OneQuick
  identifier:
    kind: Exe
    id: OneQuick.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
- name: PowerToys
  identifier:
    kind: Exe
    id: PowerToys.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: PowerToys.ColorPickerUI.exe
    comment: Target color picker dialog
    matching_strategy: Equals
  - kind: Exe
    id: PowerToys.CropAndLock.exe
    comment: Target thumbnail/cropped window
    matching_strategy: Equals
  - kind: Exe
    id: PowerToys.ImageResizer.exe
    comment: Target image resizer dialog
    matching_strategy: Equals
  - kind: Exe
    id: PowerToys.Peek.UI.exe
    comment: Target Peek popup
    matching_strategy: Equals
  - kind: Exe
    id: PowerToys.PowerLauncher.exe
    comment: PpowerLauncher popup
    matching_strategy: Equals
  - kind: Exe
    id: PowerToys.PowerAccent.exe
    comment: PowerAccent popup
    matching_strategy: Equals
- name: QtScrcpy
  identifier:
    kind: Exe
    id: QtScrcpy.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
- name: QuickLook
  identifier:
    kind: Exe
    id: QuickLook.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: QuickLook.exe
    matching_strategy: Equals
- name: ShareX
  identifier:
    kind: Exe
    id: ShareX.exe
    matching_strategy: Equals
  options:
  - border_overflow
  - tray_and_multi_window
- name: SnippingTool
  identifier:
    kind: Exe
    id: SnippingTool.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: SnippingTool.exe
    matching_strategy: Equals
- name: SystemSettings
  identifier:
    kind: Exe
    id: SystemSettings.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: Shell_Dialog
    matching_strategy: Legacy
- name: Task Manager
  identifier:
    kind: Exe
    id: Taskmgr.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: TaskManagerWindow
    matching_strategy: Legacy
- name: VRCX
  identifier:
    kind: Exe
    id: VRCX.exe
    matching_strategy: Equals
  options:
  - tray_and_multi_window
- name: Visual Studio Code
  identifier:
    kind: Exe
    id: Code.exe
    matching_strategy: Equals
  options:
  - border_overflow
- name: WebStorm
  identifier:
    kind: Exe
    id: webstorm64.exe
    matching_strategy: Equals
  options:
  - object_name_change
  - tray_and_multi_window
  float_identifiers:
  - kind: Class
    id: SunAwtDialog
    comment: Targets JetBrains IDE popups and floating windows
    matching_strategy: Equals
- name: Windows Console (conhost.exe)
  identifier:
    kind: Class
    id: ConsoleWindowClass
    matching_strategy: Equals
  options:
  - force
- name: Windows Explorer
  identifier:
    kind: Exe
    id: explorer.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Class
    id: OperationStatusWindow
    comment: Targets copy/move operation windows
    matching_strategy: Legacy
  - kind: Title
    id: Control Panel
    matching_strategy: Legacy
- name: Windows Installer
  identifier:
    kind: Exe
    id: msiexec.exe
    matching_strategy: Equals
  float_identifiers:
  - kind: Exe
    id: msiexec.exe
    matching_strategy: Equals
